//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jaz15.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int Id { get; set; }
        public System.Guid UID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string Tel { get; set; }
        public string Instagram { get; set; }
        public Nullable<bool> RSVP { get; set; }
        public Nullable<int> Chair { get; set; }
        public int TableId { get; set; }
    
        public virtual Table Table { get; set; }
    }
}
